In [288]:
import numpy as np
from itertools import permutations, product

### 一、2-3阶行列式求解，对角线法制

In [77]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flip_a = np.flip(a, axis=1)
print(a)
# 主对角元素
x1 = np.diagonal(a, offset=0)
x2 = np.concatenate([np.diagonal(a, offset=1), np.diagonal(a, offset=-2)])
x3 = np.concatenate([np.diagonal(a, offset=2), np.diagonal(a, offset=-1)])

# 副对角元素
y1 = np.diagonal(flip_a, offset=0)
y2 = np.concatenate([np.diagonal(flip_a, offset=1), np.diagonal(flip_a, offset=-2)])
y3 = np.concatenate([np.diagonal(flip_a, offset=2), np.diagonal(flip_a, offset=-1)])

value = np.prod(x1) + np.prod(x2) + np.prod(x3) - np.prod(y1) - np.prod(y2) - np.prod(y3)
value, np.linalg.det(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(0, 0.0)

### 二、n阶行列式求解

In [212]:
# 行列式项
n = 5
a = np.random.randint(0, 10, n * n).reshape(n, n)
x = np.arange(n).reshape(1, -1)
y = np.array(list(permutations([i for i in range(n)])))
x = x.repeat(len(y), axis=0)
# a[x, y]


In [213]:
# 计算逆序数
n = 5
pailie = np.array(list(permutations([i for i in range(n)])))
z = []
for i in pailie:
    p = 1
    nixu = 0
    while p < len(i):
        for j in i[:p]:
            if j > i[p]:
                nixu += 1
        p += 1
    z.append([nixu])
z = np.array(z)
# np.hstack([pailie, z])

In [221]:
# n阶行列式展开
n = 5
a = np.random.randint(0, 10, n ** 2).reshape(n, n)

# x循序排列
x = np.arange(n).reshape(1, -1)
# y全排列
y = np.array(list(permutations(range(5))))
x = x.repeat(y.shape[0], axis=0)
# 根据逆序数获得符号
z = []
for i in y:
    nixu = 0
    p = 1
    while p < len(i):
        for j in i[:p]:
            if j > i[p]:
                nixu += 1
        p += 1
    z.append([1 if nixu % 2 == 0 else -1])
z = np.array(z)

# 根据xy坐标获取元素
xy1 = a[x, y]
# 获取每个排列数的乘积
xy2 = xy1.prod(axis=1, keepdims=True)
# 加上符号后求和
(xy2 * z).sum(), np.linalg.det(a)

(-7776, -7776.000000000009)

In [228]:
# n阶行列式的交换
# 交换两行，行列式符号改变
from random import sample
n = 5
a = np.random.randint(0, 10, n*n).reshape(n, n)
b = a.copy()
c = a.copy()
x, y = sample(list(range(n)), 2)
b[x], b[y] = a[y], a[x]
c[:, x] = a[:, y]
c[:, y] = a[:, x]

np.linalg.det(a), np.linalg.det(b), np.linalg.det(c)

(10906.999999999982, -10906.999999999982, -10907.000000000002)

### 三、行列式的性质

In [231]:
# 行列式的装置值等于原行列式值
n = 5
a = np.random.randint(0, 9, n*n).reshape(n, n)
np.linalg.det(a), np.linalg.det(a.T)

(2289.999999999999, 2289.999999999999)

In [232]:
# 两行两列交换行列式值变号

In [235]:
# 两行两列相同，行列式值为0
n = 5
a = np.random.randint(0, 9, n*n).reshape(n, n)
b = a.copy()
a[3] = a[1]
b[:, 1] = b[:, 3]
np.linalg.det(a), np.linalg.det(b)

(0.0, 0.0)

In [240]:
# 行或者列的公因子可以提出来
n = 5
a = np.random.randint(0, 9, n*n).reshape(n, n)
b = a.copy()
b[3] = b[3] * 5

np.linalg.det(a) * 5,  np.linalg.det(b)

(-28899.999999999985, -28900.00000000002)

In [247]:
# 将某一行的元素 * 一个数加到另一行上，行列式结果不变

n = 5
a = np.random.randint(0, 9, n*n).reshape(n, n)
b = a.copy()
a[3] += a[1] * 3

np.linalg.det(a),  np.linalg.det(b)

(-114.00000000000134, -114.00000000000053)

### 四、行列式按行、列展开

In [264]:
# 余子式
from random import sample
n = 5
x, y = sample(list(range(n)), 2)
a = np.random.randint(0, 10, n*n).reshape(n, n)
M = np.linalg.det(np.delete(np.delete(a, x, axis=0), y, axis=1))
M

340.0000000000001

In [265]:
# 代数余子式
from random import sample
n = 5
x, y = sample(list(range(n)), 2)
a = np.random.randint(0, 10, n*n).reshape(n, n)
M = np.linalg.det(np.delete(np.delete(a, x, axis=0), y, axis=1))
A = (-1)**(x + y) * M
A

-255.99999999999994

In [279]:
# 行展开, 可以根据0最多的行或者列快速求解行列式值
n = 5
# 行列坐标
x = np.array([0]*n)
y = np.arange(5)
xy = np.stack([x, y], axis=-1)

a = np.random.randint(0, 10, n*n).reshape(n, n)

# 很据行、列展开公式进行求解
values = 0
for i, j in xy:
    M = np.linalg.det(
        np.delete(np.delete(a, i, axis=0), j, axis=1)
    )
    values += (-1)**(i + j) * a[i, j] * M

values, np.linalg.det(a)

(894.0000000000018, 893.9999999999997)

In [345]:
# 范德蒙行列式

a = np.ones((5, 5))
for i in range(a.shape[0]):
    if i >= 1:
        if i == 1:
            a[i] = [1, 2, 3, 4, 5]
        else:
            a[i] = a[1] ** i
z = list(range(5))
xy = np.array(list(product(z, z)))
xy = xy[xy[:, 0] > xy[:, 1]]
print(xy[:, 0])
print(xy[:, 1])
print(a[1])
np.prod(a[1][xy[:, 0]] - a[1][xy[:, 1]]), np.linalg.det(a)

[1 2 2 3 3 3 4 4 4 4]
[0 0 1 0 1 2 0 1 2 3]
[1. 2. 3. 4. 5.]


(288.0, 288.0000000000013)

In [346]:
# 异乘变0定理

### 五、克莱姆法则

In [357]:
weights = np.array([[1, 1, 1], [1, -1, 5], [-1, 1, 6]])
res = np.array([1, 6, 9])

D = np.linalg.det(weights)
D1 = weights.copy()
D1[:, 0] = res
D1 = np.linalg.det(D1)
D2 = weights.copy()
D2[:, 1] = res
D2 = np.linalg.det(D2)
D3 = weights.copy()
D3[:, 2] = res
D3 = np.linalg.det(D3)

x1 = D1 / D
x2 = D2 / D
x3 = D3 / D
x1, x2, x3

(-0.5909090909090908, 0.22727272727272727, 1.3636363636363635)